# Generated by Django 5.1.6 on 2025-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
