# Generated by Django 5.1.6 on 2025-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_remove_produto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('INFANTIL', 'Infantil'), ('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('CALÇADOS', 'Calçados'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
