# Generated by Django 5.1.6 on 2025-08-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_produto_categoria_alter_produto_descricao'),
    ]

    operations = [
    ]
